### ISSUE TITLE
parallel npm start script issue 

### ISSUE THREAD

**Issue by riffAt2013** [kohrongying/11ty-blog-starter#13]
tailwindcss not giving output file on the dist  `_site/assets/styles/tailwind.css`.

possible solution: 
`npm start` script executes two scripts on parallel, an 11ty serve and tailwind parser. the serve request comes first and not let the other script to execute. also the tailwind `--watch` flag maybe collides with 11ty `--serve`?

`npx tailwindcss -i ./tailwind.css -o _site/assets/styles/tailwind.css & npx @11ty/eleventy --serve` fixes it, should I do a pull request? still a newbie :|

**Comment by riffAt2013** [comment]
without `--watch`, styling updates doesn't work properly it seems, any other solutions? :(

**Comment by kohrongying** [comment]
Hi @riffAt2013, I am unable to replicate your issue on my local machine.

My setup:
- OS: MacOS
- npm: 8.6.0

Here are some of my steps:
1. Fresh git clone
2. npm install
3. npm start

Open `_site/assets/styles/tailwind.css` and see
```css
/*
! tailwindcss v3.0.18 | MIT License | https://tailwindcss.com
*/

/*
1. Prevent padding and border from affecting element width. (https://github.com/mozdevs/cssremedy/issues/4)
2. Allow adding a border to an element by just adding a border-width. (https://github.com/tailwindcss/tailwindcss/pull/116)
*/

*,
::before,
::after {
  box-sizing: border-box;
  /* 1 */
  border-width: 0;
  /* 2 */
  border-style: solid;
  /* 2 */
  border-color: #e5e7eb;
  /* 2 */
}
...
```

Alternatively, run each command in separate windows, using tmux? 😰 
Sorry I'm not too sure why this happening for you :(
